# Generated by Django 3.1.1 on 2020-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_auto_20200903_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twituser',
            name='displayname',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
